version: "3"

services:
  db:
    container_name: home-training_db
    image: postgres:11.4-alpine
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./back/tmp/db:/var/lib/postgresql/data

  back:
    container_name: home-training_back
    build: back/
    volumes:
      - ./back:/app
    depends_on:
      - db
    # ports:
    #   - 3000:3000

  front:
    container_name: home-training_front
    build: front
    command: npm run dev
    volumes:
      - ./front/src:/app
    ports:
      - 8080:3000
    depends_on:
      - back